### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ianwremmel** [ianwremmel/bowman#2]
# Phase 0 - internal tooling
- [x] build before publish
- [x] fix greenkeeper
- [x] pull args from commit messages
# Phase I - publish tooling
- [x] exec
  - discourage use as an npm script
- [ ] deps
  - [X] list <package> [--include-transitive] [--local-only] [--dependents]
  - [x] generate [package]
  - [ ] ~check [package] --no-extraneous --no-missing --validate-dev~ #6
- [x] version 
  - [x] next
    - [x] version next - get latest version from all packages and use conventional changelog rules to determine next version
  - [x] set
    - [x] version set [--all --fetch] - get current published versions
    - [x] version set [target][--all] - set version in all packages
    - [x] version set [target][--changed] - set version in all changed packages (if tooling changed or if `#force-publish`, all packages)
- [X] ~list [--changed]~
- [X] ~list [--testable]~
- [X] ~list [--testable] [--changed]~
- [X] ~list [--testable] [--changed] [--include-transitive]~
- [X] ~list [--testable] [--changed] [--include-transitive] [--ignore-tooling]~
- [ ] ~list [--testable] [--changed] [--include-transitive] [--npm]~
- [ ] ~list updated~
- [x] list
- [x] list [--changed]
- [x] list testable
- [x] list testable [--changed]
- [ ] ~list testable [--changed] [--include-transitive]~
- [x] list testable [--changed] [--ignore-tooling]
- [x] check [--exit-status]
  - [x] check testable 
    - [x] check testable [--changed]
    - [x] check testable [--changed]
    - [x] check testable [--changed] [--ignore-tooling]
  - [x] check publishable
# Phase II - transformation
- [x] pkgshift
  - [ ] defaults
  - [x] sort
  - [ ] set correct repository path
- [ ] codeshift
  - [ ] copyright banner/no-leading-whitespace
- [ ] readmeshift
  - [ ] standard-readme
# Phase III - build
- [ ] build - babel transform
- [ ] bundle - webpack/rollup bundling
- [ ] changelog - prepare changelog
# Phase IV - local customizations
- [ ] support local additions via a .bowman directory or --bowman-dir
  - directory structure should be something like
  ```
    .bowman
    ├── commands
    └── mods
        ├── code
        └── package
  ```
# Phase V - testing
- [ ] sauce 
    - [ ] start
    - [ ] run
      - autostart/autostop
    - [ ] stop
- [ ] lint js
- [ ] lint styles
- [ ] lint packagenames
- [ ] test [--raw] [--node] [--browser] [--documentation] [--integration] [--unit] [packageName]
  - determine if tests are node-only/browser-only
# Phase VI - serve
- [ ] serve <packageName>
# Phase VII - replace existing tools
- [ ] unlern
